---
output:
  html_document: default
  pdf_document: default
  word_document: default
---

# Introduction {#intro}

Research methods build the base for innovation in many areas. As one domain recently learning engineering looks at the challenge of continuous renewal and innovation in educational technologies and the evluation of these innovations.



## Definitions and terminology {#definitions}

Technology enhanced learning is about exploring the:
Learning potential (goal) and usability (goal) of (design of/affordances of) digital technology x) for person (actor(s) a,b,c)  in context(s)  as studied by the educational system designer/researcher

Defining Technology
Defining Enhancement
Defining Learning
 
Technology enhanced learning research is a systematic approach to design and assess  digital technology with respect to increasing:
Effectiveness
Efficiency
Enjoyability/Attractiveness
Accessibility
Usefulness enhancements (=usability and utility) (see also SAMR framework)


Is it method, techniques or methodologies? See next part 
See external glossary

Understanding the difference between methods and methodology is of paramount importance. Method is simply a research tool, a component of research – say for example, a qualitative method such as interviews. Methodology is the justification for using a particular research method.

## Frameworks, Theory and Models

2.2 Framework—Theory–Model: Distinctions among these three analytical tools are
especially important for analysts to remember.
2.2.1 Framework identifies, categorizes, and organizes those factors deemed most
relevant to understanding some phenomenon.
2.2.2 Theory posits general causal relationships among some subsets of these
variables or categories of factors, designating some types of factors as
especially important and others as less critical for explanatory purposes.
2.2.3 Model specifies the specific functional relationships among particular variables
or indicators that are hypothesized to operate in some well-defined
set of conditions.

See: An Introduction to IAD and the Language of the Ostrom
Workshop: A Simple Guide to a Complex Frameworkpsj_401 169..184
Michael D. McGinnis


## The Research Process {#process}

## Choosing a strategy {#strategy}

Abstract: The chapter will introduce the main dimensions of TEL research, which are theoretical assumptions and models, technology development and innovation methods, contextual embedding, daily practice and pedagogy, as also empirical evidence generated from formative and summative evaluations. Based on the main objectives of a research project different examples for TEL research are described and classified.  Objectives in TEL research range from targeting for the innovation of new technologies based on theoretical assumptions, implementing technology in daily practice, generating research evidence for enhancing theoretical underpinnings or embedding technology in practices to enhance learning. To ensure sound research quality and outcomes TEL researchers on the one hand need to prioritize objectives and on the other hand need to be aware of the relations between the different dimensions. The chapter introduces guiding questions for the four dimensions of TEL research projects and how these should be used to balance research and create high quality research outcomes. The examples given also illustrate different TEL research projects and how these have combined different methods in a process which links and considers all four dimensions. Strategic guidance for the TEL researcher is implemented with the TheTePrEv Framework which helps to identify blind spots and missing components for methodological choices in research projects.



## Interdisciplinary work

In general TEL is an interdisciplinary field bringing together different research backgrounds as also different research objectives. While engineering sciences mostly have the objective to create and design artefacts, the social and behavioural sciences more target humans interaction with these artefacts and the effects therefrom. In that sense TEL projects bring together these objectives on a high level, in a first step you therefore have to answer different questions:
What kind of technology do you want to use? What are the main characteristics of the technology you want to use and how do you specify the main activity that users do with your software or artefact?

What are the enhancements you expect from the use of such technology and what are your expected outcomes? How do you plan to measure these outcomes?

What is the main learning you would like to see in the educational context? How you you describe learning in that context? What problems and barriers are there in the current educational implementation and setting? Are the problems in the environmental settings or are there problems of users for learning from the available support?




