# Example chapter



On the role of technology in technology-enhanced learning research
Marco Kalz




Abstract
This chapter reflects on the different perspectives of technology on technology-enhanced learning research. The TEL domain and its use of technology is discussed in a historical context against the educational technology domain. Different perspectives and resulting challenges are discussed.

Keywords:  TEL, technology, technological determinism, social determinism, middle-ground



Introduction
There has been an ongoing critique regarding the role of educational theory for research on educational technology (Ravenscroft, 2001). On the other hand, the role of technology itself has been seldom discussed in the field of technology-enhanced learning. This chapter discusses the different perspectives on the role of technology in technology-enhanced learning research. To position the field of technology-enhanced learning in relation to earlier research fields, it is useful to discuss related definitions. In an early definition of educational technology, the AECT Task Force on Definition and Terminology points out that educational technology should not be confused with the application of technology in education. According to the AECT (1977) the field of educational technology defines technology in a broad sense as the application of an “integrated process involving people, procedures, ideas, devices, and organization, for analyzing problems and devising, implementing, evaluating and managing solutions to those problems, in all aspects of human learning”. This definition goes beyond technology in the sense of technics and includes a variety of methods and approaches which do not involve technological artifacts.

Later, Reiser (2001) proposes the term instructional design and technology to avoid confusing it with the term instructional media which he interprets as the application of “computers, videos, CD-Roms, overhead and slide-projectors and other types of hardware and software”. Both fields have explicitly given themselves a broader definition than the use of the development and integration of technological artifacts in an educational context. The domain of technology-enhanced learning is explicitly focusing on a narrower definition. We define technology-enhanced learning research as a systematic approach to design, apply and analyse effects of digital technology with respect to increasing effectiveness, efficiency, enjoyability/attractiveness, accessibility of learning. In this definition, the design or application of digital technology into an educational context is central to the field. TEL does not focus on all types of technologies but explicitly focuses on digital technology. This definition has important implications for the identity of the field as a whole since the design of digital artifacts requires expertise from computer science while the application and evaluation requires expertise from educational science and psychology. Based on this combination of competences and expertise, the field of technology-enhanced learning has been from the start regarded as an interdisciplinary discipline (Kalz & Specht, 2014). Nonetheless, the role of technology itself has not been sufficiently critically reflected in the field and there are implicit patterns of argumentation and assumptions about the role of technology which we would like to discuss in the next section.
 
Different roles of technology
One of the most prominent discussion in the field relates to a basic assumption about which discipline should lead in the development of interventions and solutions. The slogan “pedagogy first, technology second” is an often-repeated statement that many people from the educational field communicate based on the assumption that the only real innovation in teaching and learning should come from the pedagogy formulating requirements which the technical developers need to realize. On the other hand, there is a pervasive statement that a new technology is going to revolutionize education assuming that the introduction of a new technology will lead directly to better teaching or learning.
What is common to both positions is the implicit deterministic stance that is used as a starting point. Chandler (1995) differentiates between two types of determinisms. On the one hand, there is a technological determinism, on the other hand there is a social determinism. Technological determinism is connected to a number of assumptions about the character and effects of technology.

Often, reductionist and mechanistic models are used which are assuming a simple cause-and-effect relationship to explain phenomena. Instead of taking into account individual, environmental or contextual variables, effects of technology are generalized to such a high level that technology is regarded as the source of progress or innovation. As second assumptions connected to technological determinism is the aspect of reification. According to Chandler (1995) reification means to treat technology as if it was “a single material thing with a homogeneous, undifferentiated character”. 

As second assumptions connected to technological determinism is the aspect of reification. According to Chandler (1995) reification means to treat technology as if it was “a single material thing with a homogeneous, undifferentiated character”. In times of pervasive computerization of our society and environments and the connection and dependency of technologies on each other it is nearly impossible to generalize effects from one technology to the other. In addition, authors like Berry (2014) point to the ongoing softwarization of our society leading to a “post-digital world in which the digital has become completely bound up with and constitutive of everyday life and the so-called digital economy”. This has led also to a higher level of personalization and adaptation options for end-users taking the discussion regarding the reification of technology on another level because even the same digital technology can work differently for two users. Example of this are prominent search engines which are showing different results for search terms depending on the user profile or mobile apps which follow the notification preferences of the user rather the pre-designed notification of an app developed for learning.  
Another aspect of this discussion is the assumption that machines can be divided into single parts and they offer a regular behavior. This assumption cannot be transferred to the use of technology in a social context because “the use of complex and interacting technologies may have implications which are not always entirely intended or predicted. And the complex fabric of social reality cannot be neatly analyzed into component factors” (Chandler, 1995).

The neutrality of technology also known as the instrumental view of technology usage can be also seen as a deterministic perspective. Based on this perspective, technology itself is regarded as a kind of transport medium that does not add any affordances or qualities to the learning process. A very famous example from the educational technology domain is the debate between Richard Clark and Robert Kozma (see Clark 1994, Kozma, 1995) about the influence of “media” on learning. Clark (1994) supports the perspective of technological neutrality and states that technology itself has no influence on learning. In opposition, Kozma (1995) answered to this statement and argued that media/technologies have in itself traits that can have effects on learning.

Another dimension of the technological determinism standpoint is the assumption that technology is acting autonomously. Chandler (1995) frames this perspective as follows: “Rather than as a product of society and an integral part of it, technology is presented as an independent, self-controlling, self-determining, self-generating, self-propelling, self-perpetuating and self-expanding force”. A special flavor of this perspective is the so-called anthropomorphism which projects unique human traits (purposeful behavior) on technology. This position ignores the fact that technology is made by humans and that all functionalities embedded into technology are in the end also designed by man. In recent times, where machine learning and artificial intelligence is also applied in the context of technology-enhanced learning, the discussion on autonomy of technology is getting a completely new perspective. To take a recent example, artificial neural networks are applied to solve different kind of problems (learning rules of games, pattern and image recognition etc.), but their internal function is working like a black box that is outside of the capabilities of humans.

An often-repeated stance also in an educational context is the paradigm of the unstoppable technological progress also called the technological imperative. This perspective assumes that technology will inevitably lead to changes in society, education etc. and that this progress is unstoppable. This perspective and assumption of change is in that sense problematic as societies can always consciously accept or reject technologies. Especially ethical dimensions of the application of specific technologies can produce a public discourse that ends up in a decision not to adopt a technological progress. Several examples of this come from the medical field like stem cell research or the use of new test approaches for disability screening of babies. In technology-enhanced learning this discourse between potential application and realized application of technology is especially visible in the field of learning analytics (Greller & Drachsler, 2014) in which the public discourse is inevitably connected to the discussion about data protection and conflicts between individual integrity and the potential benefit for learning.
In the same line of thinking, Pannabecker (1991) has criticized that we regularly talk about the impact of technology. He poses that this metaphor “implies that technology is a discrete force with a discernible direction and influence”.
 
The other extreme position that is also very famous especially in educational domains is to completely deny any effects of technology resulting into the other extreme deterministic perspective which we call here again following Chandler (1995) social determinism. Social determinism is assuming that social factors are shaping society and that technology itself is not having any natural affordances that also influence the societal development.

Establishing a middle ground for technology-enhanced learning research
After having introduced the different perspectives and deterministic stances the question arises if there is also a middle-ground position that is able to overcome the extreme positions.
